on:
  push:
    branches:
      - main

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run package
        run: npx vsce package --no-git-tag-version --no-update-package-json -o "./extension.vsix"
      - name: Publish VS Code Extension
        run: npx vsce publish --packagePath"./extension.vsix" --no-git-tag-version --no-update-package-json -p ${{ secrets.VS_MARKETPLACE_TOKEN}}
