on:
  push:
    branches:
      - main

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Publish to Visual Studio Marketplace
        run: npm ci && npm i --location=global vsce && vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}
